In [2]:
import numpy as np

array1 = np.array([0, 1, 2])
array2 = np.array([2, 1, 0])
print("\nOriginal array1:")
print(array1)
print("\nOriginal array2:")
print(array2)
print("\nCovariance matrix of the said arrays:\n",np.cov(array1, array2))


Original array1:
[0 1 2]

Original array2:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]
